### ISSUE TITLE
cntp.ovh site down

### ISSUE THREAD

**Issue by lectrode** [sen87/CNTP#4]
site appears to be down. also verified with a 3rd party site checker

**Comment by sen87** [comment]
Hi,

yeah the whole server ist down since 12:30 (UTC+2) according to my monitoring and is unreachable.
Just came back home so I'll have to check what going on. The provider is reachable.

**Comment by sen87** [comment]
Hm bad news maybe...

There are some weird log entries in the VPS Panel of this instance:
![Screenshot_20220728_223704](https://user-images.githubusercontent.com/16217416/181632800-d83eb0ed-d512-4998-afa1-667cecfe2a54.png)
I did not perform any of those actions. Either this is an administration oopsie from the provider (which I suspect because of the "root" entries) or the access to the VPS Panel was compromised. :(

*Today at 12:32 pm | Deleting VPS | Deleting VPS Done*
If this is true and they can't restore it, the server will be offline for a while due to time constraints on my side (maybe till sunday).
Nothing will be lost though, since everything is backed up (on my end). Ticket is out to the provider.

**Comment by lectrode** [comment]
glad to hear nothing is gone for good. hopefully it's just a mistake on the provider's part

**Comment by sen87** [comment]
Hi,

good news! The server is up again:

```
I've had a look at this for you.
First of all I confirm that what happened here is not a VPS compromising case.
What actually happened here is an automatic live migration of your VPS to another node, as we've discovered some technical issues with the node your VPS has previously hosted on since 2017.
To avoid a potential service disruption for customers hosted on that node, we've live migrated all VPSes to other nodes.
This is a background process, that usually doesn't cause any issues at all and isn't noticed by customers as the VPS remains online during such process.

With your VPS somehow something went wrong with this process, keeping the "new" VPS in paused (suspended) state. I've manually took it out of this state, and rebooted it afterwards. It seems to be doing fine now, as I can ping the IP without any issues.

The delete entry in your logs is related to the "old" VPS, that was running on the problematic VPS.
As the entire VPS was copied 1:1 to another node, our system deletes the old instance to avoid any chance of double running VPSes.
Apologies for the confusion this might have caused.
```
Well, shit happens. I've run into similar live migration issues on proxmox clusters in the past (although they are probbaly using ESXi).
Nice that they have good support at least. :)

**Comment by lectrode** [comment]
Awesome. Glad it was a quick fix and they were able to get it back up!

Very familiar with ESXi, although I haven't had that kind of issue in the 8 years I've been working with it. vCenter has been very reliable in that regard. Then again, I haven't used the docker functionality on it yet; that's something I'm looking more into. The instances I've worked with have primarily hosted server VMs.

(In fact, the scenario they describe doesn't seem possible with vCenter/ESXi, as any live migration process either ends with a running VM at the destination, or a fails with a complete rollback - meaning the VM is still running where it originally was)

Either way, thanks for the quick response!
